trigger:
- master

strategy:
  matrix:
    stable:
      rustup_toolchain: stable

pool:
  vmImage: ubuntu-latest

steps:
  - script: |
      curl https://sh.rustup.rs -sSf | sh -s -- -y --default-toolchain $RUSTUP_TOOLCHAIN
      echo "##vso[task.setvariable variable=PATH;]$PATH:$HOME/.cargo/bin"      
    displayName: install rust
  - script: cargo build --manifest-path ./import_stock_price/Cargo.toml
    displayName: cargo build
  - script: cargo test --manifest-path ./import_stock_price/Cargo.toml
    displayName: cargo test